//! The pinned schema inventory, and the test that holds this module to it.
//!
//! `vendor/schema.json` is generated by `scripts/vendor-codex.sh` from `codex app-server
//! generate-json-schema` at the tag in `vendor/PIN`. It lists, for every definition this harness
//! speaks, the field names and enum values that build declares. It also records the JSON-RPC
//! method discriminators this crate uses in each direction. The tests below assert that every name
//! [`crate::protocol`] writes or reads is one of them.
//!
//! What this catches is the failure mode a type-checked wire cannot: a field renamed upstream
//! compiles here perfectly and fails on a user's machine as a `-32602`, or worse, as an option
//! silently ignored. What it does not catch is a field *added* upstream, which is deliberate —
//! this harness reads a subset on purpose, and every addition would otherwise be a red build.

/// The schema inventory this harness was written against.
pub const INVENTORY: &str = include_str!("../../vendor/schema.json");

/// The upstream tag `vendor/` was generated from.
pub const PIN: &str = include_str!("../../vendor/PIN");

/// The oldest `codex` this harness drives.
///
/// The pinned build, not an older one: the app-server's item families and the `thread`/`turn`
/// method names changed shape inside the 0.15x series, and a floor below the pin would be a claim
/// about builds nothing here was ever checked against.
pub const MINIMUM_CODEX_VERSION: &str = "0.154.0";

#[cfg(test)]
mod tests {
    use super::{INVENTORY, MINIMUM_CODEX_VERSION, PIN};
    use serde_json::Value;

    fn inventory() -> Value {
        serde_json::from_str(INVENTORY).expect("expected the vendored inventory to be JSON")
    }

    fn definition(name: &str) -> Value {
        inventory()["definitions"]
            .get(name)
            .cloned()
            .unwrap_or_else(|| panic!("expected {name} in the vendored inventory, received none"))
    }

    fn properties(name: &str) -> Vec<String> {
        definition(name)["properties"]
            .as_array()
            .map(|values| {
                values
                    .iter()
                    .filter_map(|value| value.as_str().map(str::to_owned))
                    .collect()
            })
            .unwrap_or_default()
    }

    fn values(name: &str) -> Vec<String> {
        definition(name)["values"]
            .as_array()
            .map(|values| {
                values
                    .iter()
                    .filter_map(|value| value.as_str().map(str::to_owned))
                    .collect()
            })
            .unwrap_or_default()
    }

    fn methods(direction: &str) -> Vec<String> {
        inventory()["methods"]
            .get(direction)
            .and_then(Value::as_array)
            .map(|values| {
                values
                    .iter()
                    .filter_map(|value| value.as_str().map(str::to_owned))
                    .collect()
            })
            .unwrap_or_default()
    }

    fn assert_declares(definition_name: &str, fields: &[&str]) {
        let declared = properties(definition_name);
        let missing: Vec<&str> = fields
            .iter()
            .copied()
            .filter(|field| !declared.iter().any(|name| name == field))
            .collect();
        assert!(
            missing.is_empty(),
            "expected {definition_name} to declare {missing:?}, received {declared:?}; \
             re-run scripts/vendor-codex.sh and reconcile src/protocol/"
        );
    }

    fn assert_accepts(definition_name: &str, wire_values: &[&str]) {
        let declared = values(definition_name);
        let missing: Vec<&str> = wire_values
            .iter()
            .copied()
            .filter(|value| !declared.iter().any(|name| name == value))
            .collect();
        assert!(
            missing.is_empty(),
            "expected {definition_name} to accept {missing:?}, received {declared:?}; \
             re-run scripts/vendor-codex.sh and reconcile src/protocol/"
        );
    }

    fn assert_declares_methods(direction: &str, names: &[&str]) {
        let declared = methods(direction);
        let missing: Vec<&str> = names
            .iter()
            .copied()
            .filter(|name| !declared.iter().any(|value| value == name))
            .collect();
        assert!(
            missing.is_empty(),
            "expected {direction} to declare {missing:?}, received {declared:?}; \
             re-run scripts/vendor-codex.sh and reconcile src/protocol/"
        );
    }

    /// The gate and the pin are one number. Two would drift, and the one that drifted would be the
    /// one a host reads out of `GateVerdict::VersionTooOld`.
    #[test]
    fn the_version_gate_is_the_version_the_schema_was_pinned_at() {
        assert_eq!(
            PIN.trim(),
            format!("rust-v{MINIMUM_CODEX_VERSION}"),
            "expected vendor/PIN to name the gated version"
        );
        assert_eq!(
            inventory()["codexVersion"].as_str(),
            Some(MINIMUM_CODEX_VERSION),
            "expected the inventory to be generated at the gated version"
        );
    }

    #[test]
    fn the_method_discriminators_are_the_ones_the_pinned_build_declares() {
        use crate::protocol::{approvals, method, notifications};

        assert_declares_methods(
            "ClientRequest",
            &[
                method::INITIALIZE,
                method::THREAD_START,
                method::THREAD_RESUME,
                method::THREAD_READ,
                method::THREAD_LIST,
                method::TURN_START,
                method::TURN_STEER,
                method::TURN_INTERRUPT,
                method::REVIEW_START,
                method::MODEL_LIST,
                method::ACCOUNT_READ,
                method::ACCOUNT_RATE_LIMITS_READ,
                method::PERMISSION_PROFILE_LIST,
            ],
        );
        assert_declares_methods("ClientNotification", &[method::INITIALIZED]);
        assert_declares_methods(
            "ServerRequest",
            &[
                approvals::method::COMMAND_EXECUTION_APPROVAL,
                approvals::method::FILE_CHANGE_APPROVAL,
                approvals::method::TOOL_CALL,
                approvals::method::TOOL_REQUEST_USER_INPUT,
                approvals::method::MCP_ELICITATION,
                approvals::method::PERMISSIONS_APPROVAL,
                approvals::method::CHATGPT_AUTH_TOKENS_REFRESH,
                approvals::method::ATTESTATION_GENERATE,
                approvals::method::LEGACY_EXEC_COMMAND_APPROVAL,
                approvals::method::LEGACY_APPLY_PATCH_APPROVAL,
            ],
        );
        assert_declares_methods(
            "ServerNotification",
            &[
                notifications::method::THREAD_STARTED,
                notifications::method::TURN_STARTED,
                notifications::method::TURN_COMPLETED,
                notifications::method::ITEM_STARTED,
                notifications::method::ITEM_COMPLETED,
                notifications::method::AGENT_MESSAGE_DELTA,
                notifications::method::REASONING_TEXT_DELTA,
                notifications::method::REASONING_SUMMARY_TEXT_DELTA,
                notifications::method::COMMAND_EXECUTION_OUTPUT_DELTA,
                notifications::method::MCP_TOOL_CALL_PROGRESS,
                notifications::method::FILE_CHANGE_PATCH_UPDATED,
                notifications::method::THREAD_TOKEN_USAGE_UPDATED,
                notifications::method::ACCOUNT_RATE_LIMITS_UPDATED,
                notifications::method::SERVER_REQUEST_RESOLVED,
                notifications::method::ERROR,
            ],
        );
    }

    #[test]
    fn the_handshake_fields_are_the_ones_the_pinned_build_declares() {
        assert_declares("InitializeParams", &["clientInfo", "capabilities"]);
        assert_declares("ClientInfo", &["name", "title", "version"]);
        assert_declares("InitializeResponse", &["userAgent", "platformOs"]);
    }

    #[test]
    fn the_thread_fields_are_the_ones_the_pinned_build_declares() {
        assert_declares(
            "ThreadStartParams",
            &[
                "cwd",
                "model",
                "approvalPolicy",
                "sandbox",
                "approvalsReviewer",
                "config",
            ],
        );
        assert_declares(
            "ThreadResumeParams",
            &[
                "threadId",
                "cwd",
                "model",
                "approvalPolicy",
                "sandbox",
                "excludeTurns",
                "config",
            ],
        );
        assert_declares("Thread", &["id", "preview", "name", "cwd", "updatedAt"]);
        assert_declares("ThreadReadParams", &["threadId", "includeTurns"]);
        assert_declares("ThreadReadResponse", &["thread"]);
        assert_declares(
            "ThreadListParams",
            &[
                "cursor",
                "limit",
                "cwd",
                "sortKey",
                "sortDirection",
                "sourceKinds",
                "archived",
            ],
        );
        assert_declares("Thread", &["recencyAt"]);
        assert_accepts("ThreadSortKey", &["recency_at"]);
        assert_accepts("SortDirection", &["desc"]);
        assert_accepts("ThreadSourceKind", &["cli", "exec", "appServer"]);
        assert_declares("ThreadListResponse", &["data", "nextCursor"]);
    }

    #[test]
    fn the_turn_fields_are_the_ones_the_pinned_build_declares() {
        assert_declares(
            "TurnStartParams",
            &[
                "threadId",
                "input",
                "model",
                "effort",
                "approvalPolicy",
                "sandboxPolicy",
                "approvalsReviewer",
            ],
        );
        assert_declares("TurnSteerParams", &["threadId", "input", "expectedTurnId"]);
        assert_declares("TurnSteerResponse", &["turnId"]);
        assert_declares("TurnInterruptParams", &["threadId", "turnId"]);
        assert_declares("Turn", &["id", "status", "error"]);
        // Upstream spells this one member snake_case among camelCase siblings. The inventory is
        // where that claim is checked, because a rename to `textElements` would otherwise show up
        // as a turn whose input the server silently refuses.
        assert_declares("UserInput", &["text", "text_elements", "url"]);
        assert_accepts("UserInput", &["text", "image"]);
        assert_declares(
            "TurnError",
            &["message", "additionalDetails", "codexErrorInfo"],
        );
        assert_accepts("CodexErrorInfo", &["usageLimitExceeded", "other"]);
        assert_declares(
            "CodexErrorInfo",
            &["activeTurnNotSteerable", "httpConnectionFailed"],
        );
        assert_accepts(
            "TurnStatus",
            &["inProgress", "completed", "interrupted", "failed"],
        );
    }

    #[test]
    fn the_configuration_values_are_the_ones_the_pinned_build_accepts() {
        assert_accepts("AskForApproval", &["untrusted", "on-request", "never"]);
        assert_accepts(
            "SandboxMode",
            &["read-only", "workspace-write", "danger-full-access"],
        );
        assert_accepts("ApprovalsReviewer", &["user", "auto_review"]);
    }

    #[test]
    fn the_structured_sandbox_policy_is_the_one_the_pinned_build_declares() {
        assert_declares(
            "SandboxPolicy",
            &[
                "type",
                "networkAccess",
                "writableRoots",
                "excludeTmpdirEnvVar",
                "excludeSlashTmp",
            ],
        );
        assert_accepts(
            "SandboxPolicy",
            &["readOnly", "workspaceWrite", "dangerFullAccess"],
        );
    }

    #[test]
    fn the_approval_fields_and_decisions_are_the_ones_the_pinned_build_declares() {
        assert_declares(
            "CommandExecutionRequestApprovalParams",
            &[
                "threadId",
                "turnId",
                "itemId",
                "approvalId",
                "command",
                "cwd",
                "reason",
                "proposedExecpolicyAmendment",
                "proposedNetworkPolicyAmendments",
            ],
        );
        assert_declares(
            "FileChangeRequestApprovalParams",
            &["threadId", "turnId", "itemId", "reason", "grantRoot"],
        );
        assert_declares("CommandExecutionRequestApprovalResponse", &["decision"]);
        assert_declares("FileChangeRequestApprovalResponse", &["decision"]);
        assert_accepts(
            "CommandExecutionApprovalDecision",
            &["accept", "acceptForSession", "decline", "cancel"],
        );
        assert_accepts(
            "FileChangeApprovalDecision",
            &["accept", "acceptForSession", "decline", "cancel"],
        );
        assert_declares(
            "ServerRequestResolvedNotification",
            &["threadId", "requestId"],
        );
    }

    /// The undeclared member the running server also writes. The inventory is where that claim is
    /// checked: if a later build declares it, this test fails and the harness can start reading it
    /// on purpose rather than by accident.
    #[test]
    fn the_available_decisions_member_is_still_undeclared_upstream() {
        let declared = properties("CommandExecutionRequestApprovalParams");
        assert!(
            !declared.iter().any(|name| name == "availableDecisions"),
            "expected availableDecisions to stay undeclared; it is now in the schema, so \
             src/protocol/approvals.rs can read it rather than deriving the option set"
        );
    }

    #[test]
    fn the_item_fields_are_the_ones_the_pinned_build_declares() {
        assert_declares("ItemStartedNotification", &["threadId", "turnId", "item"]);
        assert_declares("ItemCompletedNotification", &["threadId", "turnId", "item"]);
        assert_declares(
            "AgentMessageDeltaNotification",
            &["threadId", "turnId", "itemId", "delta"],
        );
        assert_declares(
            "ReasoningSummaryTextDeltaNotification",
            &["threadId", "turnId", "itemId", "delta"],
        );
        assert_accepts(
            "CommandExecutionStatus",
            &["inProgress", "completed", "failed", "declined"],
        );
        assert_declares(
            "CommandExecutionOutputDeltaNotification",
            &["threadId", "turnId", "itemId", "delta"],
        );
        assert_declares(
            "McpToolCallProgressNotification",
            &["threadId", "turnId", "itemId", "message"],
        );
        assert_declares(
            "FileChangePatchUpdatedNotification",
            &["threadId", "turnId", "itemId", "changes"],
        );
        assert_declares("FileUpdateChange", &["path", "diff"]);
    }

    #[test]
    fn the_usage_and_quota_fields_are_the_ones_the_pinned_build_declares() {
        assert_declares("ThreadTokenUsage", &["total", "last", "modelContextWindow"]);
        assert_declares(
            "TokenUsageBreakdown",
            &[
                "inputTokens",
                "cachedInputTokens",
                "cacheWriteInputTokens",
                "outputTokens",
                "reasoningOutputTokens",
                "totalTokens",
            ],
        );
        assert_declares(
            "RateLimitWindow",
            &["usedPercent", "windowDurationMins", "resetsAt"],
        );
        assert_declares("RateLimitSnapshot", &["primary", "secondary", "planType"]);
        assert_declares("AccountRateLimitsUpdatedNotification", &["rateLimits"]);
        assert_declares(
            "RateLimitSnapshot",
            &["credits", "individualLimit", "spendControlReached"],
        );
        assert_declares("CreditsSnapshot", &["hasCredits", "unlimited", "balance"]);
        assert_declares(
            "SpendControlLimitSnapshot",
            &["limit", "used", "remainingPercent", "resetsAt"],
        );
        assert_declares(
            "GetAccountRateLimitsResponse",
            &["rateLimits", "rateLimitResetCredits"],
        );
        assert_declares(
            "RateLimitResetCreditsSummary",
            &["availableCount", "credits"],
        );
        assert_declares(
            "RateLimitResetCredit",
            &[
                "id",
                "resetType",
                "status",
                "grantedAt",
                "expiresAt",
                "title",
                "description",
            ],
        );
    }

    #[test]
    fn the_account_and_model_fields_are_the_ones_the_pinned_build_declares() {
        assert_declares("GetAccountResponse", &["account", "requiresOpenaiAuth"]);
        assert_accepts("Account", &["apiKey", "chatgpt", "amazonBedrock"]);
        assert_declares("ModelListParams", &["cursor", "limit"]);
        assert_declares("ModelListResponse", &["data", "nextCursor"]);
        assert_declares(
            "Model",
            &[
                "id",
                "displayName",
                "description",
                "hidden",
                "isDefault",
                "supportedReasoningEfforts",
                "defaultReasoningEffort",
            ],
        );
        assert_declares("ReasoningEffortOption", &["reasoningEffort", "description"]);
        assert_declares("PermissionProfileListParams", &["cursor", "cwd"]);
        assert_declares("PermissionProfileListResponse", &["data", "nextCursor"]);
        assert_declares("PermissionProfileSummary", &["id", "allowed"]);
    }

    #[test]
    fn the_review_fields_are_the_ones_the_pinned_build_declares() {
        assert_declares("ReviewStartParams", &["threadId", "target"]);
        assert_declares("ReviewStartResponse", &["turn", "reviewThreadId"]);
        assert_declares(
            "ReviewTarget",
            &["type", "branch", "sha", "title", "instructions"],
        );
        assert_accepts(
            "ReviewTarget",
            &["uncommittedChanges", "baseBranch", "commit", "custom"],
        );
    }

    #[test]
    fn the_error_notification_fields_are_the_ones_the_pinned_build_declares() {
        assert_declares(
            "ErrorNotification",
            &["threadId", "turnId", "error", "willRetry"],
        );
    }
}
